version: '3.3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    container_name: ${APP_NAME}_db
    ports:
      - '5432:5432'
    restart: always
    networks:
      - blog-api-net

  web:
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile
    command: python manage.py runserver ${APP_HOST}:${APP_PORT}
    volumes:
      - ../app:/usr/src/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file: ../app/.env
    depends_on:
      - db
    container_name: ${APP_NAME}
    restart: always
    networks:
      - blog-api-net

volumes:
    postgres_data:

networks:
  blog-api-net:
    driver: bridge
